apiVersion: apps/v1
kind: Deployment
metadata:
  name: skmirza-organicfood-deploy
  labels:
    app: skmirza-organicfood-deploy-lb01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: skmirza-organicfood-app
  template:
    metadata:
      labels:
        app: skmirza-organicfood-app
    spec:
      containers:
      - name: skmirza-organicfood-container
        image: sameer014/skmirza-organicfood-img:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: skmirza-organicfood-np-service
  labels:
    app: skmirza-organicfood-np-app
spec:
  selector:
    app: skmirza-organicfood-app

  type: NodePort
  ports:
  - nodePort: 30019
    port: 8086
    targetPort: 8086
